bash:
  label: Bash
  permalink: /bash
  description: Bash Shell

fish:
  label: Fish
  permalink: /fish
  description: Fish Shell

tensorflow:
  label: TensorFlow
  permalink: /tensorflow
  description: TensorFlow tag description

python:
  label: Python
  permalink: /python
  description: Python tag description

jupyter-notebook:
  label: Jupyter Notebook
  permalink: /jupyter-notebook
  description: Jupyter Notebook tag description

youtube:
  label: YouTube
  permalink: /youtube
  description: YouTube tag description

ai:
  label: AI
  permalink: /ai
  description: AI tag description

windows:
  label: Windows
  permalink: /windows
  description: Windows tag description

shortcuts:
  label: Shortcuts
  permalink: /shortcuts
  description: Shortcuts tag description

linux:
  label: Linux
  permalink: /linux
  description: Linux tag description

automation:
  label: Automation
  permalink: /automation
  description: Automation tag description

google-sheets:
  label: Google Sheets
  permalink: /google-sheets
  description: Google Sheets tag description

books:
  label: Books
  permalink: /books
  description: Books tag description

data-science:
  label: Data Science
  permalink: /data-science
  description: Data Science tag description

data:
  label: Data
  permalink: /data
  description: Data tag description

gpu:
  label: GPU
  permalink: /gpu
  description: GPU tag description  

venv:
  label: Virtual Environments
  permalink: /venv
  description: Virtual Environments tag description

deep-learning:
  label: Deep Learning
  permalink: /deep-learning
  description: Deep Learning tag description

ubuntu:
  label: Ubuntu
  permalink: /ubuntu
  description: Ubuntu tag description
  
nvidia:
  label: NVIDIA
  permalink: /nvidia
  description: NVIDIA tag description

drivers:
  label: Drivers
  permalink: /drivers
  description: Drivers tag description

cuda:
  label: CUDA
  permalink: /cuda
  description: CUDA tag description

ollama:
  label: Ollama
  permalink: /ollama
  description: Ollama tag description        